export default {
  "login": "YuryLayeuski",
  "id": 16660845,
  "node_id": "MDQ6VXNlcjE2NjYwODQ1",
  "avatar_url": "https://avatars.githubusercontent.com/u/16660845?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/YuryLayeuski",
  "html_url": "https://github.com/YuryLayeuski",
  "followers_url": "https://api.github.com/users/YuryLayeuski/followers",
  "following_url": "https://api.github.com/users/YuryLayeuski/following{/other_user}",
  "gists_url": "https://api.github.com/users/YuryLayeuski/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/YuryLayeuski/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/YuryLayeuski/subscriptions",
  "organizations_url": "https://api.github.com/users/YuryLayeuski/orgs",
  "repos_url": "https://api.github.com/users/YuryLayeuski/repos",
  "events_url": "https://api.github.com/users/YuryLayeuski/events{/privacy}",
  "received_events_url": "https://api.github.com/users/YuryLayeuski/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Yury Layeuski",
  "company": "Side Real Estate",
  "blog": "",
  "location": "San Francisco",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 24,
  "public_gists": 0,
  "followers": 2,
  "following": 0,
  "created_at": "2016-01-12T05:32:56Z",
  "updated_at": "2021-04-20T22:20:42Z"
};
